# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import prakt.models


class Migration(migrations.Migration):

    dependencies = [
        ('prakt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='inf',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x98\xd0\xbd\xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd0\xb0\xd1\x86\xd0\xb8\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xbc\xd0\xb0\xd1\x82\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'),
        ),
        migrations.AddField(
            model_name='org',
            name='maildir',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xbf\xd0\xb0\xd0\xbf\xd0\xba\xd0\xb8 \xd0\xb2 \xd0\xbf\xd0\xbe\xd1\x87\xd1\x82\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xbc \xd1\x8f\xd1\x89\xd0\xb8\xd0\xba\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='file',
            field=models.FileField(upload_to=prakt.models.file_upload, verbose_name=b'\xd0\xa4\xd0\xb0\xd0\xb9\xd0\xbb'),
        ),
    ]
